alias su='su -l'
alias cal='ncal -b'
alias mutt-pers='mutt -F "$HOME/.mutt/personal.rc"'
alias mutt-info='mutt -F "$HOME/.mutt/info.rc"'
alias mutt-ugent='mutt -F "$HOME/.mutt/ugent.rc"'
alias mutting='screen -c "$HOME/.mutt/screen.rc"'
