(require 'package)
(push '("marmalade" . "http://marmalade-repo.org/packages/")
      package-archives )
(push '("melpa" . "http://melpa.milkbox.net/packages/")
      package-archives)
(package-initialize)
(if (not (package-installed-p 'use-package))
    (progn
      (package-refresh-contents)
      (package-install 'use-package)))
(require 'use-package)
(setq use-package-always-ensure t)
(use-package evil)
(evil-mode 1)
(setq inhibit-startup-message t)
(set-face-attribute 'default nil :height 100)
(global-linum-mode t)
