[accounts]
    [accounts.prive]
        host =  "vps.paretje.be"
        username =  "kevin@paretje.be"
        password_cmd = "pass show email/kevin@paretje.be"
        sync_interval = 300
        periodic_sync_condition = "! 3gusage"

    [accounts.notes]
        host = "vps.paretje.be"
        username = "notes@online-urbanus.be"
        password_cmd = "pass show email/notes@online-urbanus.be"
        sync_interval = 900
        imap_idle = false
        periodic_sync_condition = "! 3gusage"

    [accounts.ugent]
        host =  "outlook.office365.com"
        username =  "Kevin.Velghe@UGent.be"
        password_cmd = "pass show email/Kevin.Velghe@UGent.be"
        sync_interval = 300
        imap_idle = false
        periodic_sync_condition = "! 3gusage"

    [accounts.ionbot-support]
        host =  "imap.mailprotect.be"
        username =  "support@ionbot.cloud"
        password_cmd = "pass show email/support@ionbot.cloud"
        sync_interval = 300
        periodic_sync_condition = "! 3gusage"
