[accounts]
    [accounts.prive]
        host =  "vps.paretje.be"
        username =  "kevin@paretje.be"
        password_cmd = "pass show email/kevin@paretje.be"
        sync_interval = 300
        periodic_sync_condition = "! 3gusage"

    [accounts.notes]
        host = "vps.paretje.be"
        username = "notes@online-urbanus.be"
        password_cmd = "pass show email/notes@online-urbanus.be"
        sync_interval = 900
        imap_idle = false
        periodic_sync_condition = "! 3gusage"

    [accounts.ugent]
        host =  "owa.ugent.be"
        username =  "Kevin.Velghe@UGent.be"
        password_cmd = "pass show email/Kevin.Velghe@UGent.be"
        sync_interval = 300
        periodic_sync_condition = "! 3gusage"

    [accounts.senso2me]
        host =  "imap.mailprotect.be"
        username =  "kevin.velghe@senso2.me"
        password_cmd = "pass show email/kevin.velghe@senso2.me"
        sync_interval = 300
        periodic_sync_condition = "! 3gusage"
