#!/bin/sh
if [ -z "$BACKPORTS_DEPS" ]; then
        exit
fi

BACKPORTS_SUITE="$DIST-backports"

echo "deb ${MIRRORSITE} ${BACKPORTS_SUITE} ${COMPONENTS}" > /etc/apt/sources.list.d/backports.list

echo "Package: ${BACKPORTS_DEPS}" > /etc/apt/preferences.d/99backports
echo "Pin: release a=${BACKPORTS_SUITE}" >> /etc/apt/preferences.d/99backports
echo "Pin-priority: 500" >> /etc/apt/preferences.d/99backports
cat /etc/apt/preferences.d/99backports
apt-get update
