#!/bin/bash
init() {
    return
}
query_entries() {
    domain="$1"

    while read -r line ; do
        if [[ "$line" =~ "attribute.username = " ]] ; then
            files+=${line#${BASH_REMATCH[0]}}
            break
        fi
    done < <( secret-tool search --all domain "$domain" 2>&1 )
}
open_entry() {
    username="$1"
    password=$(secret-tool lookup domain "$domain" username "$username")
}
