#!/usr/bin/env bash
QUTE_FIFO="/dev/null" . "$QUTE_DATA_DIR/userscripts/password_fill"
echo "hint inputs" >> "$QUTE_FIFO"
sleep 1
echo "leave-mode" >> "$QUTE_FIFO"
echo "fake-key <Ctrl-a>" >> "$QUTE_FIFO"
echo "fake-key <Delete>" >> "$QUTE_FIFO"
sleep 0.25s
echo "insert-text ${username}" >> "$QUTE_FIFO"
echo "fake-key <Tab>" >> "$QUTE_FIFO"
sleep 0.25s
echo "insert-text ${password}" >> "$QUTE_FIFO"
