#!/usr/bin/env bash
. "$QUTE_DATA_DIR/userscripts/password_fill"
echo "fake-key ${username}" >> "$QUTE_FIFO"
echo "fake-key <Tab>" >> "$QUTE_FIFO"
echo "fake-key ${password}" >> "$QUTE_FIFO"
echo "enter-mode insert" >> "$QUTE_FIFO"
