#!/bin/bash -e
mozify_url() {
    moz_url="${1##*://}" # temporally remove protocol specification
    moz_url="${moz_url%%\?*}" # remove GET parameters
    moz_url="${moz_url%%/*}" # remove directory path
    moz_url="${1%%://*}://${moz_url}"
}

# TODO: duplication of code, this function is defined in 3 scripts now
simplify_url() {
    simple_url="${1##*://}" # remove protocol specification
    simple_url="${simple_url%%\?*}" # remove GET parameters
    simple_url="${simple_url%%/*}" # remove directory path
    simple_url="${simple_url%:*}" # remove port
    simple_url="${simple_url##www.}" # remove www. subdomain
}

mozify_url "$QUTE_URL"
simplify_url "$QUTE_URL"
domain="$simple_url"
username=""
password=""

while read -r line ; do
    if [[ "$line" =~ "attribute.username = " ]] ; then
	username="${line#${BASH_REMATCH[0]}}"
    elif [[ "$line" =~ "secret = " ]] ; then
	password="${line#${BASH_REMATCH[0]}}"
    fi
done < <( secret-tool search --unlock hostname "$moz_url" 2>&1 )

if [ "$password" != "" ]; then
    printf '%s' "$password" | secret-tool store --label="qutebrowser password for $domain" domain "$domain" username "$username"
else
    echo "message-error 'No password found'" > "$QUTE_FIFO"
fi
