#!/bin/sh -e
simplify_url() {
    simple_url="${1##*://}" # remove protocol specification
    simple_url="${simple_url%%\?*}" # remove GET parameters
    simple_url="${simple_url%%/*}" # remove directory path
    simple_url="${simple_url%:*}" # remove port
    simple_url="${simple_url##www.}" # remove www. subdomain
}

simplify_url "$QUTE_URL"
domain="$simple_url"
username="$(yad --entry --fixed --on-top --title="Username" --image="config-users")"
password="$(yad --entry --hide-text --fixed --on-top --title="Password" --image="dialog-password")"
printf '%s' "$password" | secret-tool store --label="qutebrowser password for $domain" domain "$domain" username "$username"
