#!/usr/bin/env bash
. "$QUTE_DATA_DIR/userscripts/password_fill"
echo "fake-key -g ${username}" >> "$QUTE_FIFO"
echo "fake-key -g <Enter>" >> "$QUTE_FIFO"
echo "fake-key -g ${password}" >> "$QUTE_FIFO"
echo "fake-key -g <Enter>" >> "$QUTE_FIFO"
