#!/bin/bash
host=$(ls -1 "$HOME/.password-store/kodi" | sed 's/\.gpg$//' | dmenu)
kodi-send "$host" "$(pass "kodi/$host" | tail -1 | sed 's/^login:\s*//')" "$(pass "kodi/$host" | head -1)" "$QUTE_URL"
